fissa:
    resource: "@FissaBundle/Resources/config/routing.yml"
    prefix:   /

doc_depot_api:
    type: rest
    prefix: /api
    resource: "@DocDepotApiBundle/Resources/config/as_routing.yml"

doc_depot_site:
    resource: "@DocDepotSiteBundle/Controller/"
    type:     annotation
    prefix:   /

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
