<?php

namespace DocDepot\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelationConfianceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationConfianceRepository extends EntityRepository
{

	public function save(RelationConfiance $relationConfiance){
		$this->getEntityManager()->persist($relationConfiance);
	}


	public function commit(){
		$this->getEntityManager()->flush();
	}

	public function findByBeneficiaire($beneficiaire){
		 return $this->createQueryBuilder('a')
                    ->where('a.beneficiaire_id = :beneficiaire_id')
                    ->setParameter('beneficiaire_id', $beneficiaire->getId())
                    ->getQuery()
                    ->getResult();
	}

	public function findByActeurSocial($acteurSocial){
		 return $this->createQueryBuilder('a')
                    ->where('a.acteur_social_id = :acteur_social_id')
                    ->setParameter('acteur_social_id', $acteurSocial->getId())
                    ->getQuery()
                    ->getResult();
	}

}
